/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

module

public import HexGramSchmidt
public import HexMatrix

public section

/-!
Integer row-lattice membership and independence for `hex-lll`,
with the row-operation lemmas showing that an adjacent swap or a
size-reduction row combination preserves the generated lattice.
-/

namespace Hex

namespace Matrix

/-- `v` lies in the integer lattice generated by the rows of `b`. -/
@[expose]
def memLattice (b : Matrix Int n m) (v : Vector Int m) : Prop :=
  ∃ c : Vector Int n, vecMul c b = v

end Matrix

namespace Internal

open Hex.Matrix

/-- Row combinations transport across an explicit integer row transform. -/
theorem vecMul_mul (U : Matrix Int n' n) (B : Matrix Int n m)
    (c : Vector Int n') :
    vecMul (Matrix.transpose U * c) B = vecMul c (U * B) := by
  unfold vecMul
  calc
    Matrix.transpose B * (Matrix.transpose U * c) =
        (Matrix.transpose B * Matrix.transpose U) * c := by
          exact (Matrix.mul_assoc_vec (A := Matrix.transpose B)
            (B := Matrix.transpose U) (v := c)).symm
    _ = Matrix.transpose (U * B) * c := by
          rw [← Matrix.transpose_mul_of_mul_comm]

/-- If every row of `B'` is an integer row combination of rows of `B`, then
membership in the lattice generated by `B'` implies membership for `B`. -/
theorem memLattice_of_mul_eq {B : Matrix Int n m} {B' : Matrix Int n' m}
    {U : Matrix Int n' n} {v : Vector Int m} (h : U * B = B') :
    B'.memLattice v → B.memLattice v := by
  intro hv
  rcases hv with ⟨c, hc⟩
  refine ⟨Matrix.transpose U * c, ?_⟩
  rw [vecMul_mul U B, h, hc]

/-- Two explicit integer row transforms in opposite directions prove equality of
the generated lattices. -/
theorem memLattice_iff_of_mul_eq {B B' : Matrix Int n m} {U V : Matrix Int n n}
    (hU : U * B = B') (hV : V * B' = B) (v : Vector Int m) :
    B.memLattice v ↔ B'.memLattice v := by
  constructor
  · exact memLattice_of_mul_eq hV
  · exact memLattice_of_mul_eq hU

end Internal

namespace Matrix

/-- The rows of `b` are linearly independent, witnessed by positivity of each
executable leading Gram determinant. -/
@[expose]
def independent (b : Matrix Int n m) : Prop :=
  GramSchmidt.Int.independent b

end Matrix

namespace Internal

open Hex.Matrix

/-- `memLattice_of_rowSwap_memLattice` states that any vector in the lattice
generated by `rowSwap b i j` also lies in the lattice generated by `b`. -/
theorem memLattice_of_rowSwap_memLattice
    (b : Matrix Int n m) (i j : Fin n) (v : Vector Int m) :
    Matrix.memLattice (Matrix.rowSwap b i j) v → Matrix.memLattice b v := by
  intro hv
  rcases hv with ⟨c, hc⟩
  let S : Matrix Int n n := Matrix.rowSwap (Matrix.identity (R := Int) n) i j
  have hrow : S * b = Matrix.rowSwap b i j := by
    rw [Matrix.rowSwap_mul, Matrix.identity_mul]
  refine ⟨Matrix.transpose S * c, ?_⟩
  calc
    Matrix.vecMul (Matrix.transpose S * c) b
        = Matrix.transpose b * (Matrix.transpose S * c) := rfl
    _ = (Matrix.transpose b * Matrix.transpose S) * c := by
      rw [Matrix.mul_assoc_vec]
    _ = Matrix.transpose (S * b) * c := by
      rw [Matrix.transpose_mul_of_mul_comm]
    _ = Matrix.transpose (Matrix.rowSwap b i j) * c := by
      rw [hrow]
    _ = Matrix.vecMul c (Matrix.rowSwap b i j) := rfl
    _ = v := hc

/-- `rowSwap_memLattice_iff` states that swapping rows `i` and `j` of `b`
preserves lattice membership in both directions. -/
theorem rowSwap_memLattice_iff
    (b : Matrix Int n m) (i j : Fin n) (v : Vector Int m) :
    Matrix.memLattice (Matrix.rowSwap b i j) v ↔ Matrix.memLattice b v := by
  constructor
  · exact memLattice_of_rowSwap_memLattice b i j v
  · intro hv
    have hv' : Matrix.memLattice (Matrix.rowSwap (Matrix.rowSwap b i j) i j) v := by
      rwa [Matrix.rowSwap_rowSwap]
    exact memLattice_of_rowSwap_memLattice (Matrix.rowSwap b i j) i j v hv'

/-- `memLattice_of_rowAdd_memLattice` states that any vector in the lattice
generated by `rowAdd b src dst c` also lies in the lattice generated by `b`. -/
theorem memLattice_of_rowAdd_memLattice
    (b : Matrix Int n m) (src dst : Fin n) (c : Int) (v : Vector Int m) :
    Matrix.memLattice (Matrix.rowAdd b src dst c) v → Matrix.memLattice b v := by
  intro hv
  rcases hv with ⟨w, hw⟩
  let S : Matrix Int n n := Matrix.rowAdd (Matrix.identity (R := Int) n) src dst c
  have hrow : S * b = Matrix.rowAdd b src dst c := by
    simp [S, Matrix.rowAdd_mul, Matrix.identity_mul]
  refine ⟨Matrix.transpose S * w, ?_⟩
  calc
    Matrix.vecMul (Matrix.transpose S * w) b
        = Matrix.transpose b * (Matrix.transpose S * w) := rfl
    _ = (Matrix.transpose b * Matrix.transpose S) * w := by
      rw [Matrix.mul_assoc_vec]
    _ = Matrix.transpose (S * b) * w := by
      rw [Matrix.transpose_mul_of_mul_comm]
    _ = Matrix.transpose (Matrix.rowAdd b src dst c) * w := by
      rw [hrow]
    _ = Matrix.vecMul w (Matrix.rowAdd b src dst c) := rfl
    _ = v := hw

/-- `rowAdd_memLattice_iff` states that adding `c` times row `src` to a distinct
row `dst` of `b` preserves lattice membership in both directions. -/
theorem rowAdd_memLattice_iff
    (b : Matrix Int n m) {src dst : Fin n} (hne : src ≠ dst) (c : Int) (v : Vector Int m) :
    Matrix.memLattice (Matrix.rowAdd b src dst c) v ↔ Matrix.memLattice b v := by
  constructor
  · exact memLattice_of_rowAdd_memLattice b src dst c v
  · intro hv
    have hv' : Matrix.memLattice
        (Matrix.rowAdd (Matrix.rowAdd b src dst c) src dst (-c)) v := by
      rwa [Matrix.rowAdd_rowAdd_neg b c hne]
    exact memLattice_of_rowAdd_memLattice (Matrix.rowAdd b src dst c) src dst (-c) v hv'

end Internal

end Hex
