/-
Copyright (c) 2026 Lean FRO, LLC. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Kim Morrison
-/

import Hex.Conformance.Emit
import HexLLL

/-!
JSONL emit driver for the `hex-lll` oracle.

`lake exe hexlll_emit_fixtures` writes one JSONL `lattice` record per
input basis followed by one `lll` `result` record carrying Lean's
`δ`-LLL-reduced basis (with `δ = 3/4`). The companion oracle
`scripts/oracle/lll_fpylll.py` reads the same stream and re-runs the
reduction through `fpylll.LLL.reduction`, comparing the two reduced
bases via lattice equality (HNF agreement) and `δ`-reducedness rather
than literal basis equality — LLL output is not unique in general.

Coverage:

* "Known-reducible" upper-triangular bases at dimensions `2`, `3`,
  `4`, `5` constructed as `[1; k₁ 1; k₂ k₃ 1; ...]`-style rows whose
  canonical reduction collapses to the identity basis.
* One BZ-shaped triangular lattice basis: rows correspond to lifted
  local factors with a small coefficient block.

* Upper-triangular pseudo-random bases at dimensions `4`, `6`, `8`,
  `10` generated by a reproducible LCG and reduced modulo a small odd
  window so each off-diagonal entry fits in a few bits.
-/

namespace Hex.LLLEmit

open Hex.Conformance.Emit

private def lib : String := "HexLLL"

/-- Render a basis matrix as a list of integer rows for JSON emission. -/
private def basisRows (b : Matrix Int n m) : List (List Int) :=
  (List.finRange n).map fun i => (b.row i).toArray.toList

/-- Lower bound on `δ = 3/4`. -/
private theorem lll_delta_lower : (1 / 4 : Rat) < 3 / 4 := by
  grind

/-- Upper bound on `δ = 3/4`. -/
private theorem lll_delta_upper : (3 / 4 : Rat) ≤ 1 := by
  grind

/-- Emit one `(lattice, result)` pair: serialise the input basis and
the reduced basis Lean returns from `lllNative b (3/4) ...`. -/
private def emitCase (id : String) {n m : Nat} (hn : 1 ≤ n)
    (b : Matrix Int n m) : IO Unit := do
  emitLatticeFixture lib id (basisRows b)
  let r : Matrix Int n m :=
    lllNative b (3 / 4) lll_delta_lower lll_delta_upper hn
  emitResult lib id "lll" (latticeValue (basisRows r))

/-! ## Known-reducible bases.

Each basis pairs short canonical vectors with a long row that is a
fixed integer combination plus a small perturbation; reducing collapses
the long rows back toward the canonical generators. -/

private def reducible2 : Matrix Int 2 2 :=
  Matrix.ofFn fun i j =>
    match i.val, j.val with
    | 0, 0 => 1
    | 0, 1 => 12
    | 1, 1 => 1
    | _, _ => 0

private def reducible3 : Matrix Int 3 3 :=
  Matrix.ofFn fun i j =>
    match i.val, j.val with
    | 0, 0 => 1
    | 0, 1 => 7
    | 0, 2 => 13
    | 1, 1 => 1
    | 1, 2 => 5
    | 2, 2 => 1
    | _, _ => 0

private def reducible4 : Matrix Int 4 4 :=
  Matrix.ofFn fun i j =>
    match i.val, j.val with
    | 0, 0 => 1
    | 0, 1 => 9
    | 0, 2 => 17
    | 0, 3 => 23
    | 1, 1 => 1
    | 1, 2 => 4
    | 1, 3 => 11
    | 2, 2 => 1
    | 2, 3 => 6
    | 3, 3 => 1
    | _, _ => 0

private def reducible5 : Matrix Int 5 5 :=
  Matrix.ofFn fun i j =>
    match i.val, j.val with
    | 0, 0 => 1
    | 0, 1 => 5
    | 0, 2 => 11
    | 0, 3 => 19
    | 0, 4 => 31
    | 1, 1 => 1
    | 1, 2 => 3
    | 1, 3 => 8
    | 1, 4 => 14
    | 2, 2 => 1
    | 2, 3 => 4
    | 2, 4 => 9
    | 3, 3 => 1
    | 3, 4 => 5
    | 4, 4 => 1
    | _, _ => 0

/-! ## BZ-shaped triangular lattice basis.

Rows index lifted local factors and retain a small upper-triangular coefficient
block, so independence follows from the local triangular helper. -/

private def bzCoeff (factor col : Nat) : Int :=
  match factor, col with
  | 0, 0 => 1
  | 0, 1 => 1
  | 1, 1 => 1
  | 1, 2 => 1
  | 2, 2 => 1
  | 2, 3 => 1
  | _, _ => 0

private def bzBasis : Matrix Int 3 3 :=
  Matrix.ofFn fun i j =>
    bzCoeff i.val j.val

/-! ## Random integer bases.

Fully populated `n × n` integer matrices generated by a small LCG
(`xₙ₊₁ = (1103515245 · xₙ + 12345) mod 2^31`, the venerable POSIX
`rand`) and folded into `[-window, window]`. These exercise the
adjacent-swap update for `i > k` on bases that are not initially
upper-triangular. -/

private def lcgStep (x : Nat) : Nat :=
  (1103515245 * x + 12345) % 2147483648

private def lcgIterate (seed : Nat) (k : Nat) : Nat :=
  match k with
  | 0 => seed
  | k + 1 => lcgIterate (lcgStep seed) k

/-- Map a 31-bit nonnegative LCG output into a centred integer in
`[-(2*window+1)/2, (2*window+1)/2]`. -/
private def foldEntry (raw : Nat) (window : Nat) : Int :=
  (Int.ofNat (raw % (2 * window + 1))) - Int.ofNat window

private def randomBasis (n : Nat) (seed window : Nat) : Matrix Int n n :=
  Matrix.ofFn fun i j =>
    if j.val < i.val then
      0
    else if i = j then
      Int.ofNat (window + 1)
    else
      foldEntry (lcgIterate seed (i.val * n + j.val + 1)) window

private def random4 : Matrix Int 4 4 := randomBasis 4 1 30
private def random6 : Matrix Int 6 6 := randomBasis 6 7 30
private def random8 : Matrix Int 8 8 := randomBasis 8 13 30
private def random10 : Matrix Int 10 10 := randomBasis 10 23 30

end Hex.LLLEmit

open Hex.LLLEmit in
def main : IO Unit := do
  emitCase "reducible/d2" (by decide) reducible2
  emitCase "reducible/d3" (by decide) reducible3
  emitCase "reducible/d4" (by decide) reducible4
  emitCase "reducible/d5" (by decide) reducible5
  emitCase "bz/p5k2/3factors" (by decide) bzBasis
  emitCase "random/d4" (by decide) random4
  emitCase "random/d6" (by decide) random6
  emitCase "random/d8" (by decide) random8
  emitCase "random/d10" (by decide) random10
